% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={STAT 6021 Homework 1},
  pdfauthor={Kip McCharen},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{STAT 6021 Homework 1}
\author{Kip McCharen}
\date{7/13/2020}

\begin{document}
\maketitle

\hypertarget{question-1a-old-faithful}{%
\subsection{Question 1a, Old Faithful}\label{question-1a-old-faithful}}

\begin{itemize}
\tightlist
\item
  Response variable: \emph{waiting}, time elapsed (in years) between
  eruption events
\item
  Predictor variable: \emph{eruptions}, time elapsed (in minutes) during
  an eruption event
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\#\#(1b) Scatterplot

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(}\KeywordTok{names}\NormalTok{(faithful))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "eruptions" "waiting"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(}\KeywordTok{head}\NormalTok{(faithful))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   eruptions waiting
## 1     3.600      79
## 2     1.800      54
## 3     3.333      74
## 4     2.283      62
## 5     4.533      85
## 6     2.883      55
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(}\KeywordTok{summary}\NormalTok{(faithful))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    eruptions        waiting    
##  Min.   :1.600   Min.   :43.0  
##  1st Qu.:2.163   1st Qu.:58.0  
##  Median :4.000   Median :76.0  
##  Mean   :3.488   Mean   :70.9  
##  3rd Qu.:4.454   3rd Qu.:82.0  
##  Max.   :5.100   Max.   :96.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(}\KeywordTok{nrow}\NormalTok{(faithful))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 272
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(faithful}\OperatorTok{$}\NormalTok{eruptions, faithful}\OperatorTok{$}\NormalTok{waiting,}
     \DataTypeTok{ylab=}\StringTok{\textquotesingle{}Waiting time(min)\textquotesingle{}}\NormalTok{,}
     \DataTypeTok{xlab=}\StringTok{\textquotesingle{}Eruption Time(min)\textquotesingle{}}\NormalTok{,}
     \DataTypeTok{main=}\StringTok{\textquotesingle{}Plot for waiting time and eruption time\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{STAT6021_HW1_KipMcCharen_files/figure-latex/setup-1.pdf}
I would describe the relationship between the two variables as grouped
at extremes. There is no clear straight line in the graph.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\#\#(1c) correlation

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor}\NormalTok{(faithful}\OperatorTok{$}\NormalTok{waiting, faithful}\OperatorTok{$}\NormalTok{eruptions)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9008112
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# bp\_data\_LSR \textless{}{-} lm(BP\textasciitilde{}weight)}
\CommentTok{\# summary(bp\_data\_LSR)}
\CommentTok{\# B1 \textless{}{-} bp\_data\_LSR$coef[2]}
\CommentTok{\# print(B1)}
\end{Highlighting}
\end{Shaded}

Even though the correlation is 0.9, this interpretation is not extremely
reliable due to the obviously imperfect relationship in the graph.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\#\#(1d) Fit linear regression

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{result \textless{}{-}}\StringTok{ }\KeywordTok{lm}\NormalTok{(faithful}\OperatorTok{$}\NormalTok{waiting}\OperatorTok{\textasciitilde{}}\NormalTok{faithful}\OperatorTok{$}\NormalTok{eruptions)}
\KeywordTok{summary}\NormalTok{(result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = faithful$waiting ~ faithful$eruptions)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -12.0796  -4.4831   0.2122   3.9246  15.9719 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(>|t|)    
## (Intercept)         33.4744     1.1549   28.98   <2e-16 ***
## faithful$eruptions  10.7296     0.3148   34.09   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.914 on 270 degrees of freedom
## Multiple R-squared:  0.8115, Adjusted R-squared:  0.8108 
## F-statistic:  1162 on 1 and 270 DF,  p-value: < 2.2e-16
\end{verbatim}

anova(result)

\#SSE + SSR = SST \#R squared is 0.8

\#sigma hat squared is about 35 - estimated variance print(5.914 \^{} 2)

\#y intercept doesn't make sense in this case \#F value is enormous

\#null and alternative hypotheses \#βˆ1 == 0 \#βˆ1 interpretation: A
1-minute increase in the length of eruption will increase the waiting
time by 10.7296 minutes on average.

\#critical value \#qf function? \#conclusion: there is a linear
relationship between the variables

\#what is the critical value? \# 1 - alpha\\
\# df1 = 1 \# df2 = n - 2 \# look at anova and take DF from there

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\item
  Interpret the values of beta hat 1, beta hat 0 contextually. Does the
  value of beta hat 0 make sense in this context?
\item
  Use the anova() function to produce the ANOVA table for this linear
  regression. What is the value of the ANOVA F statistic? What null and
  alternative hypotheses are being tested here? What is a relevant
  conclusion based on this ANOVA F statistic? 3.876 f critical value qf
  qf(0.95, 1,270)
\end{enumerate}

writing out hypothesis statement -\textgreater{} we reject the null
because f stat is significantly greater than f value. Just checking if
there's a linear correlation between the two.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{6}
\item
  Obtain the 95\% confidence interval for the slope, beta1. Is this
  confidence interval consistent with your conclusion from part 1f?
  Briefly explain. CI 10.1 and 11.3 beta1 is way outside, so we can
  reject it
\item
  The latest eruption at Old Faithful lasted for 3.5 minutes. Obtain an
  appropriate 95\% interval that predicts the waiting time for the next
  eruption. just plug 3.5 into slope of the line equation? thought he
  wanted a prediction interval, same as previous except chg key to
  prediction 59.36 and 82.69
\item
  What is the 95\% interval for the average waiting time for the next
  eruption among current eruptions that last 3.5 minutes? 71.3 and
  \_\_\_\_
\item
  Create a residual plot, an ACF plot of the residuals, and the QQ plot
  of the residuals. Based on these plots, are the regression assumptions
  met? Is your answer surprising, given the context of this data set?
  how to do residual plot?
\end{enumerate}

\hypertarget{r-required-for-this-question-we-will-use-the-cornnit-data-set-from-the-faraway-package.-be-sure-to-install-and-load-the-faraway-package-faraway-and-then-load-the-data-set.-the-data-explore-the-relationship-between-corn-yield-bushels-per-acre-and-nitrogen-pounds-per-acre-fertilizer-application-in-a-study-carried-out-in-wisconsin.}{%
\section{2. (R required) For this question, we will use the cornnit data
set from the faraway package. Be sure to install and load the faraway
package {[}faraway{]}, and then load the data set. The data explore the
relationship between corn yield (bushels per acre) and nitrogen (pounds
per acre) fertilizer application in a study carried out in
Wisconsin.}\label{r-required-for-this-question-we-will-use-the-cornnit-data-set-from-the-faraway-package.-be-sure-to-install-and-load-the-faraway-package-faraway-and-then-load-the-data-set.-the-data-explore-the-relationship-between-corn-yield-bushels-per-acre-and-nitrogen-pounds-per-acre-fertilizer-application-in-a-study-carried-out-in-wisconsin.}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(faraway)}
\KeywordTok{attach}\NormalTok{(cornnit)}
\KeywordTok{print}\NormalTok{(}\KeywordTok{names}\NormalTok{(cornnit))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "yield"    "nitrogen"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(}\KeywordTok{head}\NormalTok{(cornnit))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   yield nitrogen
## 1   115        0
## 2   128       75
## 3   136      150
## 4   135      300
## 5    97        0
## 6   150       75
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(}\KeywordTok{summary}\NormalTok{(cornnit))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      yield          nitrogen    
##  Min.   : 47.0   Min.   :  0.0  
##  1st Qu.:113.5   1st Qu.: 37.5  
##  Median :135.0   Median : 87.5  
##  Mean   :125.8   Mean   :103.4  
##  3rd Qu.:142.5   3rd Qu.:162.5  
##  Max.   :168.0   Max.   :300.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(}\KeywordTok{nrow}\NormalTok{(cornnit))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 44
\end{verbatim}

\hypertarget{a-what-is-the-response-variable-and-predictor-for-this-study-create-a-scatterplot-of-the-data-and-interpret-the-scatterplot.}{%
\section{(a) What is the response variable and predictor for this study?
Create a scatterplot of the data, and interpret the
scatterplot.}\label{a-what-is-the-response-variable-and-predictor-for-this-study-create-a-scatterplot-of-the-data-and-interpret-the-scatterplot.}}

\hypertarget{predictor-nitrogen-pounds-per-acre-of-nitrogen-fertilizer-used-on-corn-fields}{%
\section{Predictor: nitrogen, pounds per acre of nitrogen fertilizer
used on corn
fields}\label{predictor-nitrogen-pounds-per-acre-of-nitrogen-fertilizer-used-on-corn-fields}}

\hypertarget{response-yield-bushels-per-acre-of-corn-grown-in-the-fields-which-were-amended-with-nitrogen-fertilizer}{%
\section{Response: yield, bushels per acre of corn grown in the fields
which were amended with nitrogen
fertilizer}\label{response-yield-bushels-per-acre-of-corn-grown-in-the-fields-which-were-amended-with-nitrogen-fertilizer}}

\hypertarget{b-fit-a-linear-regression-without-any-transformations.-create-the-corresponding-residual-plot.-based-only-on-the-residual-plot-what-transformation-will-you-consider-first-be-sure-to-explain-your-reason.}{%
\section{(b) Fit a linear regression without any transformations. Create
the corresponding residual plot. Based only on the residual plot, what
transformation will you consider first? Be sure to explain your
reason.}\label{b-fit-a-linear-regression-without-any-transformations.-create-the-corresponding-residual-plot.-based-only-on-the-residual-plot-what-transformation-will-you-consider-first-be-sure-to-explain-your-reason.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lreg\textless{}{-}}\KeywordTok{lm}\NormalTok{(nitrogen}\OperatorTok{\textasciitilde{}}\NormalTok{yield)}
\KeywordTok{print}\NormalTok{(lreg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = nitrogen ~ yield)
## 
## Coefficients:
## (Intercept)        yield  
##    -177.663        2.235
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\DataTypeTok{x=}\NormalTok{cornnit}\OperatorTok{$}\NormalTok{nitrogen, }\DataTypeTok{y=}\NormalTok{cornnit}\OperatorTok{$}\NormalTok{yield, }
     \DataTypeTok{xlab=}\StringTok{\textquotesingle{}Pounds Per Acre\textquotesingle{}}\NormalTok{, }
     \DataTypeTok{ylab=}\StringTok{\textquotesingle{}Bushesl Per Acre\textquotesingle{}}\NormalTok{, }
     \DataTypeTok{main=}\StringTok{\textquotesingle{}Plot Corn Yield and N Fertilizer\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{STAT6021_HW1_KipMcCharen_files/figure-latex/unnamed-chunk-4-1.pdf}

\hypertarget{c-create-a-box-cox-plot-for-the-profile-loglikelihoods.-how-does-this-plot-aid-in-your-data-transformation}{%
\section{(c) Create a Box Cox plot for the profile loglikelihoods. How
does this plot aid in your data
transformation?}\label{c-create-a-box-cox-plot-for-the-profile-loglikelihoods.-how-does-this-plot-aid-in-your-data-transformation}}

\hypertarget{section}{%
\section{}\label{section}}

\hypertarget{d-perform-the-necessary-transformation-to-the-data.-re-t-the-regression-with-the-transformed-variables-and-assess-the-regression-assumptions.-you-may-have}{%
\section{(d) Perform the necessary transformation to the data. Re t the
regression with the transformed variable(s) and assess the regression
assumptions. You may
have}\label{d-perform-the-necessary-transformation-to-the-data.-re-t-the-regression-with-the-transformed-variables-and-assess-the-regression-assumptions.-you-may-have}}

\hypertarget{to-apply-transformations-a-number-of-times.-be-sure-to-explain-the-reason-behind-each-of-your-transformations.-perform-the-needed-transformations-until-the-regression-assumptions-are-met.-what-is-the-regression-equation-that-you-will-use}{%
\section{to apply transformations a number of times. Be sure to explain
the reason behind each of your transformations. Perform the needed
transformations until the regression assumptions are met. What is the
regression equation that you will
use?}\label{to-apply-transformations-a-number-of-times.-be-sure-to-explain-the-reason-behind-each-of-your-transformations.-perform-the-needed-transformations-until-the-regression-assumptions-are-met.-what-is-the-regression-equation-that-you-will-use}}

\hypertarget{section-1}{%
\section{}\label{section-1}}

\hypertarget{note-in-part-2d-there-are-a-number-of-solutions-that-will-work.-you-must-clearly}{%
\section{Note: in part 2d, there are a number of solutions that will
work. You must
clearly}\label{note-in-part-2d-there-are-a-number-of-solutions-that-will-work.-you-must-clearly}}

\hypertarget{document-your-reasons-for-each-of-your-transformations.}{%
\section{document your reasons for each of your
transformations.}\label{document-your-reasons-for-each-of-your-transformations.}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  (No R required) A substance used in biological and medical research is
  shipped by airfreight to users in cartons of 1000 ampules. The data
  consist of 10 shipments. The variables are number of times the carton
  was transferred from one aircraft to another during the shipment route
  (transfer), and the number of ampules found to be broken upon arrival
  (broken). We want to t a simple linear regression. A simple linear
  regression model is tted using R. You may assume all the regression
  assumptions are met. The corresponding output from R is shown next,
  with some values missing.
\end{enumerate}

The following values are also provided for you, and may be used for the
rest of this question: x = 1, P10 i=1 (xi 􀀀 x)2 = 10.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Calculate the value of R2, and interpret this value in context. Rsq is
  the sumsq regression / sum sqr total
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ss regr + ss resid = ss total }
\CommentTok{\# }
\CommentTok{\# from ANOVA }
\CommentTok{\#   SSR / (SSR + SSP)}
\CommentTok{\#   160 / (160 + 7.6)}
\CommentTok{\#   }
\CommentTok{\#   }
\CommentTok{\#   F == 160 / 2.2 = 72.72}
\CommentTok{\#     f critical 5.32 which is \textless{} f val}
\CommentTok{\#   t test = 8.5288}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\item
  Carry out a hypothesis test to assess if there is a linear
  relationship between the variables of interest.
\item
  Calculate a 95\% confidence interval that estimates the unknown value
  of the population slope. t multiplier \textless- 2.36 used qt test
  statistic +- multiplier * standard error
\item
  A consultant believes the mean number of broken ampules when no
  transfers are made is dierent from 9. Conduct an appropriate
  hypothesis test (state the hypotheses statements, calculate the test
  statistic, and write the corresponding conclusion in context, in
  response to his belief).
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{calculated\_t\_statistics \textless{}{-}}\StringTok{ }\FloatTok{{-}10.66}
\CommentTok{\# 4.0{-}9.0 / 4.69}
\CommentTok{\# }
\CommentTok{\# 10.2{-}9 /  SE in coefficients table}
\CommentTok{\# how do we know we\textquotesingle{}re doing intercept value and not regression?}
\CommentTok{\# equation in paragraph? 2.3? had this equation}
\CommentTok{\# no transfers means x = 0, just get y intercept }
\CommentTok{\# t statistic 1.809}
\CommentTok{\# pvalue? 0.1080}
\CommentTok{\# }
\CommentTok{\# critical value \textless{}{-} 2.306}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  (No R required) A chemist studied the concentration of a solution, y,
  over time, x, by tting a simple linear regression. The scatterplot of
  the dataset, and the residual plot from the regression model are shown
  in Figure 1.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  The prole log-likelihoods for the parameter, , of the Box-Cox power
  transfor- mation, is shown in Figure 2. Your classmate says that you
  should apply a log transformation to the response variable rst. Do
  you agree with your classmate? Be sure to justify your answer.
\item
  Your classmate is adament on applying the log transformation to the
  response variable, and ts the regression model. The R output is shown
  in Figure 3. Write down the estimated regression equation for this
  model. How do we interpret the regression coecients \^{} 1 and \^{}
  0 in context?
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Reminder: please complete the Module 1 to 4 Guided Question Set
  Participation Self- and Peer-Evaluation Questions via Test \& Quizzes
  by July 21.
\end{enumerate}

Figure 1: Scatterplot of Concentration of Solution against Time (left).
Residual Plot from SLR (right) Figure 2: Prole Log-likelihoods for
\(\lambda\) Figure 3: R Output after Transforming Response Variable.

predict.lm(lR results, sliced df) needs corresponding value online

\end{document}
