---
title: "STAT6021_Mod0Qs"
author: "Kip McCharen"
date: "7/13/2020"
output:
  pdf_document: default
---

***
# Topic 1: Sampling Distributions

1. Statistical theory tells us the distribution of the sample means with a fixed sample size, under certain circumstances. The sampling distribution is an approximation of the density histogram of the sample means. We know the sample means vary from sample to sample. The sampling distribution tells us the expected value (mean) of the distribution, and the standard deviation of the sample means.

(a) Suppose the variable X follows a normal distribution with mean $\mu$ and standard deviation $\sigma$. Consider taking random samples, each with size n, repeatedly. What is the sampling distribution of the sample mean, $\bar{x}$?

## **A:** $\bar{x}$ (the sampling distribution of the sample mean) = $\textit{N}$($\mu$, $\frac{\sigma}{\sqrt{\textit{n}}}$)

***

(b) Suppose the variable X has an unknown distribution but known mean $\mu$ and known standard deviation $\sigma$. What is the name of the statistical theory that informs us that the sampling distribution of the sample mean, $\bar{x}$, can be well-approximated by a normal distribution?

## **A:** the central limit theorem

***

2. An automatic machine in a manufacturing process produces subcomponents. The lengths of the subcomponents follow a normal distribution with a mean of 116 cm and a standard deviation of 4.8 cm. 

(a) Find the probability that one selected subcomponent is longer than 118cm.

```{R, echo=TRUE}
value = 118
sample_mean = 116
ssd = 4.8
zscore = (value - sample_mean)/ssd
print(paste("zscore: ", round(zscore, digits = 4)))

curve <- pnorm(value, mean = sample_mean, sd=ssd)
print(paste("area under the curve: ", round(1-curve, digits = 4)))
```
## **A:** the probability is ~34% that one selected subcomponent is longer than 118cm

***

(b) Find the probability that if 3 subcomponents are randomly selected, their mean length exceeds 118cm.

```{R, echo=TRUE}
original_SD = 4.8
sample_size = 3
ssd = original_SD / sqrt(sample_size)
value = 118
sample_mean = 116
zscore = (value - sample_mean)/ssd
print(paste("zscore: ", round(zscore, digits = 4)))

curve <- pnorm(value, mean = sample_mean, sd=ssd)
print(paste("area under the curve: ", round(1-curve, digits = 4)))

```
## **A:** There is about a 23.5% chance that 3 randomly selected subcomponents have a mean length > 118cm. 

***

# Topic 2: Confidence Intervals

3. What are the goals of constructing a confidence interval?

## **A:** We construct confidence intervals to be as accurate as possible in quantifying the amount of uncertainty in an estimation of plausible values for an unknown value of interest. 

***

4. How does increasing the confidence level affect the margin of error and the width of the confidence interval? Hint: sketching the standard normal distribution will be helpful.

## **A:** Therefore if we increase the confidence level, the margin of error increases.

***

5. How does increasing the sample size affect the margin of error and the width of the confidence interval? Briefly explain.

## **A** As the sample size increases, so too increases the denominator of the estimate standard deviation portion of the confidence interval equation, which will reduce the magnitude of the margin of error. In clearer language, with more samples we can assume our data will look more exactly like a normal curve and we can also assume our estimates will be more generally accurate, with less error. 

***

6. Use R to find the value of the t-multiplier when constructing a confidence interval for the mean in the following situations:
(a) 94% confidence interval with n = 49.
(b) 86% confidence interval with n = 82.
(c) 74% confidence interval with n = 150.
Hint: you will need either the qt() or pt() function.

## **A** 
```{R, echo=TRUE}
t_mult <- function(alpha=0.05, sample_size) {
  percentile = (1-(alpha / 2))
  print(paste((percentile * 100), "th percentile value in t distribution", sep = ""))
  deg_free = sample_size - 1
  t_mult <- qt(percentile, deg_free)
  print(paste("t multiplier for curr alpha/percentile:  ", t_mult))
  print("")
}
t_mult(0.06, 49)
t_mult(0.14, 82)
t_mult(0.26, 150)
```

***

7. A random sample of 100 students had a mean grade point average (GPA) of 3.2 with a standard deviation of 0.2.
(a) Calculate a 97% confidence interval for the mean GPA for all students.

## **A** 

***

(b) What is the margin of error for the confidence interval found in the previous part? What is the margin of error telling us?

## **A** 

***

(c) Based on this confidence interval, is it reasonable to say that the mean GPA of all students is 3.25 or greater?

## **A** 

if writing in rmd
	-submit both a pdf and "pure" r file
	-no need to restate the Q
	-if the answer is the simple output of an R formula, do you prefer we restate that in plain English text?
	
QT is if based on t statistic
ANOVA is if based on f statistic 
  mean sq regression (df1 for numerator)
  ---------------------
  over mean sq residual (df2 for denominator)
```{R, echo=TRUE}
n = 50
df1 = n - 1
df2 = df1 - 1
alpha <- 0.05
critical_value <- qf(1-alpha, df1, df2)
```

***
